# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-05-18 06:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fundamentals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField()),
                ('basic_eps_rs', models.FloatField(blank=True)),
                ('diluted_eps_rs', models.FloatField(blank=True)),
                ('cash_eps_in_rs', models.FloatField(blank=True)),
                ('book_value_exc_reserve_rs', models.FloatField(blank=True)),
                ('book_value_inc_reserve_rs', models.FloatField(blank=True)),
                ('dividend_rs', models.FloatField(blank=True)),
                ('revenue_from_operations_rs', models.FloatField(blank=True)),
                ('pbdit_rs', models.FloatField(blank=True)),
                ('pbit_rs', models.FloatField(blank=True)),
                ('pbt_rs', models.FloatField(blank=True)),
                ('net_profit_rs', models.FloatField(blank=True)),
                ('pbdit_margin_percent', models.FloatField(blank=True)),
                ('pbit_margin_percent', models.FloatField(blank=True)),
                ('pbt_margin_percent', models.FloatField(blank=True)),
                ('net_profit_margin_percent', models.FloatField(blank=True)),
                ('return_on_networth_percent', models.FloatField(blank=True)),
                ('return_on_capital_employed_percent', models.FloatField(blank=True)),
                ('return_on_assets_percent', models.FloatField(blank=True)),
                ('total_dept_to_equity_x', models.FloatField(blank=True)),
                ('asset_turnover_ratio_percent', models.FloatField(blank=True)),
                ('current_ratio_x', models.FloatField(blank=True)),
                ('quick_ratio_x', models.FloatField(blank=True)),
                ('inventory_turnover_ratio_x', models.FloatField(blank=True)),
                ('dividend_payout_ratio_cp_percent', models.FloatField(blank=True)),
                ('dividend_payout_ratio_np_percent', models.FloatField(blank=True)),
                ('earnings_retention_ratio_percent', models.FloatField(blank=True)),
                ('cach_earnings_retention_ratio_percent', models.FloatField(blank=True)),
                ('enterprice_value_cr', models.FloatField(blank=True)),
                ('ev_over_net_operating_revenue_x', models.FloatField(blank=True)),
                ('ev_over_ebitda_x', models.FloatField(blank=True)),
                ('marketcap_over_net_operating_revenue_x', models.FloatField(blank=True)),
                ('retention_ratios_percent', models.FloatField(blank=True)),
                ('price_over_book_x', models.FloatField(blank=True)),
                ('price_over_net_operating_revenue_x', models.FloatField(blank=True)),
                ('earnings_yield', models.FloatField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Symbols',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol_name', models.CharField(max_length=50)),
                ('market_name', models.CharField(choices=[('NSE', 'NSE MARKET'), ('BSE', 'BSE MARKET'), ('NFO', 'NFO_MARKET')], max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='fundamentals',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thanos.Symbols'),
        ),
    ]
